site_name: SixStorey Code
site_url: https://pwstorey.github.io/
theme:
  name: material
  favicon: favicon.png
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
  language: en
  icon:
    logo: fontawesome/solid/robot
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode


plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/pwstorey"  target="_blank" rel="noopener">SixStorey Limited</a>